export const LOGGING_USER_BEGIN   = 'LOGGING_USER_BEGIN';
export const LOGGING_USER_SUCCESS = 'LOGGING_USER_SUCCESS';
export const LOGGING_USER_FAILURE = 'LOGGING_USER_FAILURE';
export const POST_USER = 'POST_USER'
export const SIGNUP_USER = 'SIGNUP_USER'